import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Bath, BedDouble, Check, MapPin, Ruler } from "lucide-react";
import { ContactForm } from "@/components/ContactForm";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { formatPrice, properties } from "@/data/properties";

export function generateStaticParams() { return properties.map(p => ({ id: p.id })); }
export default async function Detail({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const property = properties.find(p => p.id === id); if (!property) notFound(); return <><div className="bg-navy text-white"><Navbar/><div className="container-page pt-28 pb-8"><Link href="/properties" className="inline-flex items-center gap-2 text-sm text-white/70 hover:text-gold"><ArrowLeft size={16}/>All properties</Link></div></div><main className="container-page py-10"><div className="grid gap-10 lg:grid-cols-[1.4fr_.6fr]"><div><div className="relative h-[420px] overflow-hidden rounded-2xl bg-slate-100"><Image src={property.image} alt={property.title} fill priority className="object-cover"/></div><div className="mt-8"><p className="eyebrow">{property.type} · {property.location}</p><h1 className="mt-2 font-display text-4xl text-navy">{property.title}</h1><p className="mt-3 text-2xl font-bold text-gold">{formatPrice(property.price)}</p><div className="mt-6 flex flex-wrap gap-5 rounded-xl bg-sand p-4 text-sm font-bold text-navy"><span className="flex items-center gap-2"><Ruler size={18} className="text-gold"/>{property.area.toLocaleString()} sq ft</span>{property.bedrooms && <span className="flex items-center gap-2"><BedDouble size={18} className="text-gold"/>{property.bedrooms} bedrooms</span>}{property.bathrooms && <span className="flex items-center gap-2"><Bath size={18} className="text-gold"/>{property.bathrooms} bathrooms</span>}</div><h2 className="mt-9 font-display text-3xl text-navy">About this property</h2><p className="mt-4 max-w-2xl leading-8 text-slate-600">{property.description}</p><h2 className="mt-9 font-display text-3xl text-navy">Key amenities</h2><ul className="mt-4 grid gap-3 sm:grid-cols-2">{property.amenities.map(a => <li className="flex items-center gap-2 text-sm text-slate-600" key={a}><span className="grid h-5 w-5 place-items-center rounded-full bg-[#f6ead3] text-gold"><Check size={13}/></span>{a}</li>)}</ul></div></div><aside><div className="sticky top-6 rounded-2xl border border-slate-100 bg-white p-6 shadow-luxe"><p className="eyebrow">Interested?</p><h2 className="mt-2 font-display text-3xl text-navy">Request details</h2><p className="mt-2 text-sm leading-6 text-slate-500">Sushil or Sachin will get back to you with a suitable viewing time.</p><div className="my-5 h-px bg-slate-100"/><ContactForm propertyId={property.id}/><a href="https://wa.me/917665074030" className="mt-3 block text-center text-sm font-bold text-emerald-700">Or chat on WhatsApp</a></div></aside></div><div className="mt-12 rounded-2xl bg-sand p-6 text-sm text-slate-600"><MapPin className="mb-2 text-gold"/><b className="text-navy">Location</b><p className="mt-1">{property.location}. Contact our team for exact location and a guided site visit.</p></div></main><Footer/></>;
}
