"use client";
import { useMemo, useState } from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PropertyCard } from "@/components/PropertyCard";
import { properties } from "@/data/properties";

export default function PropertiesPage() {
 const [query, setQuery] = useState(""); const [type, setType] = useState("All"); const [beds, setBeds] = useState("All"); const [price, setPrice] = useState("All");
 const matching = useMemo(() => properties.filter(p => (type === "All" || p.type === type) && (beds === "All" || p.bedrooms === Number(beds)) && (price === "All" || (price === "under30" ? p.price < 3000000 : p.price >= 3000000 && p.price < 6000000)) && `${p.title} ${p.location}`.toLowerCase().includes(query.toLowerCase())), [query, type, beds, price]);
 return <><div className="bg-navy pb-16 text-white"><Navbar/><div className="container-page pt-36"><p className="eyebrow text-[#edc66a]">Find your next place</p><h1 className="mt-3 font-display text-5xl">Properties to explore</h1><p className="mt-4 max-w-xl text-white/70">Browse homes, plots and commercial spaces around Bhadra.</p></div></div><main className="container-page py-10"><div className="rounded-2xl border border-slate-100 bg-white p-4 shadow-luxe"><div className="grid gap-3 lg:grid-cols-[2fr_1fr_1fr_1fr_auto]"><label className="flex items-center gap-2 rounded-xl bg-slate-50 px-4"><Search size={18} className="text-slate-400"/><input value={query} onChange={e => setQuery(e.target.value)} className="w-full bg-transparent py-3 text-sm outline-none" placeholder="Search by area or property"/></label><select aria-label="Property type" value={type} onChange={e => setType(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3 text-sm"><option>All</option><option>House</option><option>Apartment</option><option>Plot</option><option>Commercial</option><option>Villa</option></select><select aria-label="Bedrooms" value={beds} onChange={e => setBeds(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3 text-sm"><option>All</option><option value="2">2 Bedrooms</option><option value="3">3 Bedrooms</option><option value="4">4 Bedrooms</option><option value="5">5 Bedrooms</option></select><select aria-label="Price range" value={price} onChange={e => setPrice(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3 text-sm"><option>All</option><option value="under30">Under ₹30 Lakh</option><option value="30to60">₹30–60 Lakh</option></select><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-navy px-5 text-sm font-bold text-white"><SlidersHorizontal size={16}/>Filter</button></div></div><div className="mt-10 flex items-center justify-between"><p className="text-sm text-slate-500"><b className="text-navy">{matching.length}</b> properties found</p></div><div className="mt-5 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{matching.map(p => <PropertyCard key={p.id} property={p}/>)}</div>{matching.length === 0 && <div className="py-24 text-center"><p className="font-display text-3xl text-navy">Nothing found yet.</p><p className="mt-2 text-slate-500">Try a different search or contact us for more options.</p></div>}</main><Footer/></>;
}
