import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, Handshake, House, Landmark, MapPin, MessageCircle, Phone, ShieldCheck, Star, UsersRound } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PropertyCard } from "@/components/PropertyCard";
import { properties } from "@/data/properties";

const services = [[House, "Buy property", "Find a place that feels right, backed by careful local guidance."], [Landmark, "Sell property", "Position your property well and reach serious, verified buyers."], [Building2, "Rent property", "Discover well-matched homes and commercial spaces with ease."], [Handshake, "Property consultation", "Clear advice on plots, land and property decisions from local experts."]];
const reasons = [[ShieldCheck, "Verified properties", "We help you focus on opportunities with clear documentation."], [MapPin, "Local market knowledge", "Insights shaped by the streets, communities and values around Bhadra."], [BadgeCheck, "Transparent deals", "Straightforward conversations, realistic expectations and no confusion."], [UsersRound, "Dedicated support", "From your first visit to the final handover, we stay close."]];
export default function Home() { const featured = properties.filter(p => p.featured); return <><main>
 <section className="relative min-h-[750px] overflow-hidden bg-navy text-white"><Image src="/images/hero-estate.png" alt="Luxury home by Choudhary Property" fill priority className="object-cover object-[65%]"/><div className="absolute inset-0 bg-gradient-to-r from-[#061d36]/95 via-[#061d36]/75 to-[#061d36]/10"/><Navbar/><div className="container-page relative flex min-h-[750px] items-center pt-16"><div className="max-w-2xl"><p className="eyebrow text-[#edc66a]">PROPERTY EXPERTS IN BHADRA</p><h1 className="mt-5 font-display text-5xl leading-[1.06] sm:text-6xl lg:text-7xl">Find a place that feels <em className="font-normal text-[#edc66a]">like home.</em></h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/75">Your trusted partner for buying, selling and renting properties — with the local expertise to make every move feel certain.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/properties" className="button-primary">Explore properties <ArrowRight size={17}/></Link><Link href="/contact" className="button-secondary">Contact us</Link></div><div className="mt-14 flex flex-wrap gap-7 text-sm"><span><b className="block text-2xl text-gold">100+</b> Local inquiries handled</span><span><b className="block text-2xl text-gold">4.9/5</b> Client satisfaction</span></div></div></div></section>
 <section className="container-page grid gap-12 py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="relative h-[380px] overflow-hidden rounded-2xl"><Image src="/images/hero-estate.png" alt="Modern residence" fill className="object-cover object-right"/><div className="absolute bottom-5 left-5 rounded-xl bg-white p-4 shadow-luxe"><p className="font-display text-2xl text-navy">Local roots.</p><p className="text-sm text-slate-500">Thoughtful property guidance.</p></div></div><div><p className="eyebrow">About Choudhary Property</p><h2 className="mt-3 font-display text-4xl leading-tight text-navy">Property decisions deserve a trusted local partner.</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">From the first conversation to the final paperwork, Choudhary Property brings clarity, care and practical market knowledge to every property journey in Bhadra and nearby areas.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-navy hover:text-gold">Meet our team <ArrowRight size={17}/></Link></div></section>
 <section id="services" className="bg-sand py-20"><div className="container-page"><div className="max-w-xl"><p className="eyebrow">What we do</p><h2 className="mt-3 font-display text-4xl text-navy">Guidance for every kind of move.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{services.map(([Icon, title, text]) => <article key={title as string} className="rounded-2xl bg-white p-7 transition hover:-translate-y-1 hover:shadow-luxe"><div className="grid h-11 w-11 place-items-center rounded-full bg-navy text-gold"><Icon size={21}/></div><h3 className="mt-6 text-lg font-bold text-navy">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text as string}</p></article>)}</div></div></section>
 <section className="container-page py-20"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Curated opportunities</p><h2 className="mt-3 font-display text-4xl text-navy">Featured properties</h2></div><Link href="/properties" className="inline-flex items-center gap-2 text-sm font-bold text-navy hover:text-gold">See all properties <ArrowRight size={17}/></Link></div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{featured.map(property => <PropertyCard property={property} key={property.id}/>)}</div></section>
 <section className="bg-navy py-20 text-white"><div className="container-page"><div className="max-w-xl"><p className="eyebrow text-[#edc66a]">The Choudhary difference</p><h2 className="mt-3 font-display text-4xl">A confident way to find your next property.</h2></div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{reasons.map(([Icon, title, text]) => <div key={title as string} className="border-t border-white/20 pt-5"><Icon size={25} className="text-gold"/><h3 className="mt-6 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-white/60">{text as string}</p></div>)}</div></div></section>
 <section className="container-page py-20"><div className="text-center"><p className="eyebrow">Client stories</p><h2 className="mt-3 font-display text-4xl text-navy">Trusted by our community.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Rakesh Sharma", "Very professional and transparent. They helped us find a family home in the right area without any pressure."], ["Priya Devi", "The local knowledge made all the difference. Every question was answered patiently and clearly."], ["Amit Kumar", "Smooth process from visit to paperwork. I would gladly recommend Choudhary Property."]].map(([name, quote]) => <figure key={name} className="rounded-2xl border border-slate-100 p-7 shadow-sm"><div className="flex gap-1 text-gold">{[1,2,3,4,5].map(i => <Star fill="currentColor" size={15} key={i}/>)}</div><blockquote className="mt-5 leading-7 text-slate-600">“{quote}”</blockquote><figcaption className="mt-5 font-bold text-navy">{name}</figcaption></figure>)}</div></section>
 <section className="container-page pb-20"><div className="overflow-hidden rounded-3xl bg-[#b8882a] px-7 py-12 text-white md:px-14 md:py-16"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-bold tracking-[.2em] text-white/70">LET’S TALK PROPERTY</p><h2 className="mt-3 max-w-2xl font-display text-4xl">Looking for a property or ready to sell one?</h2><p className="mt-4 text-white/80">Tell us what you need and we’ll help you take the next confident step.</p></div><div className="flex flex-wrap gap-3"><a href="tel:+917665074030" className="inline-flex items-center gap-2 rounded-full bg-navy px-5 py-3 text-sm font-bold"><Phone size={17}/>Call now</a><a href="https://wa.me/917665074030" className="inline-flex items-center gap-2 rounded-full border border-white/50 px-5 py-3 text-sm font-bold"><MessageCircle size={17}/>WhatsApp</a></div></div></div></section>
 </main><Footer/></>; }
