"use client";
import { FormEvent, useState } from "react";
import { Send } from "lucide-react";

export function ContactForm({ propertyId }: { propertyId?: string }) {
 const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle");
 async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setState("sending"); const form = new FormData(e.currentTarget); const payload = Object.fromEntries(form.entries()); if (propertyId) payload.propertyId = propertyId; try { const r = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!r.ok) throw new Error(); setState("success"); e.currentTarget.reset(); } catch { setState("error"); } }
 return <form onSubmit={submit} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><input required name="name" placeholder="Your name" className="w-full rounded-lg border border-slate-200 px-4 py-3 text-sm outline-none focus:border-gold"/><input required name="phone" inputMode="tel" placeholder="Phone number" className="w-full rounded-lg border border-slate-200 px-4 py-3 text-sm outline-none focus:border-gold"/></div><input name="email" type="email" placeholder="Email address (optional)" className="w-full rounded-lg border border-slate-200 px-4 py-3 text-sm outline-none focus:border-gold"/><textarea required name="message" rows={3} defaultValue={propertyId ? "I would like to know more about this property." : ""} placeholder="How can we help?" className="w-full resize-none rounded-lg border border-slate-200 px-4 py-3 text-sm outline-none focus:border-gold"/><button disabled={state === "sending"} className="button-primary w-full disabled:opacity-60">{state === "sending" ? "Sending…" : <><Send size={16}/> Request property details</>}</button>{state === "success" && <p className="text-center text-sm font-medium text-emerald-700">Thank you — we’ll contact you shortly.</p>}{state === "error" && <p className="text-center text-sm text-red-600">Something went wrong. Please call us directly.</p>}</form>;
}
